name: Publish DockerHub

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.27.1"]

    steps:
      - uses: actions/checkout@v7
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}

      - name: Validate Go code
        working-directory: ./
        run: go vet ./...

  publish:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Authenticate to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v7
        with:
          push: true
          context: ./
          tags: ${{ vars.DOCKERHUB_USERNAME }}/demo:${{ github.sha }}
